{
  "model_config": "cs336_basics/configs/models/gpt2_small.yaml",
  "data": "data/TinyStoriesV2-GPT4-train.tokenized.npy",
  "val_data": "data/TinyStoriesV2-GPT4-valid.tokenized.npy",
  "save_path": "models/ts_small",
  "trainer": {
    "batch_size": 16,
    "tot_steps": 66000,
    "warmup_steps": 5000,
    "cooldown_steps": 5000,
    "learning_rate": 0.001,
    "cooldown_learning_rate": 0.00001,
    "seqlen": 512,
    "beta1": 0.9,
    "beta2": 0.99,
    "weight_decay": 0.1
  }
}