{
  "base_model_ckpt": "models/OLMo-2-0425-1B",
  "base_model_format": "olmo_hf",
  "task_name": "gsm8k",
  "prompt_template": "alignment/prompts/r1_zero.prompt",
  "save_path": "models/rl/olmo2_1B_gsm8k/base_sft",
  "train_data": "data/gsm8k/train.jsonl",
  "val_data": "data/gsm8k/test.jsonl",
  "logging_level": "ERROR",
  "inference_backend": "sft",
  "inference_sft_field_name": "answer",
  "inference_sft_run_lllm_eval": true,
  "val_step": 80,
  "rollout_save_step": 40,
  "ckpt_save_step": 200,
  "trainer": {
    "batch_size": 64,
    "tot_steps": 800,
    "learning_rate": 0.00002,
    "gradient_clipping": 2.0,
    "group_size": 1,
    "gradient_accumulation_steps": 32,
    "rollout_batch_size": 48,
    "rollout_temperature": 1.0,
    "rollout_max_new_tokens": 512,
    "baseline": "none",
    "advantage_normalizer": "none",
    "loss_normalization": "sequence"
  }
}